{
 "title": "Hotel Review Ratings",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Average processing time ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "hotel_review_avg_processing_time_ms /1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average rating",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "hotel_review_avg_review_rating", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average review length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "hotel_review_avg_review_length", "legendFormat": "__auto" }
   ]
  }
 ]
}