{
 "title": "Apache Spark Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "All Jobs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "metrics_spark_app_driver_DAGScheduler_job_allJobs_Number{group=\"spark\", instance=\"driver\", job=\"spark-driver\"}"
    }
   ]
  },
  {
   "title": "Active Jobs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "metrics_spark_app_driver_DAGScheduler_job_activeJobs_Number{group=\"spark\", instance=\"driver\", job=\"spark-driver\"}"
    }
   ]
  },
  {
   "title": "No Of Workers",
   "type": "singlestat",
   "description": "No of currently running stages",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "metrics_master_workers_Number{group=\"spark\", instance=\"master\", job=\"spark-master\"} ",
     "legendFormat": "maxMem_MB"
    }
   ]
  },
  {
   "title": "No Of Alive Workers",
   "type": "singlestat",
   "description": "No of currently running stages",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "metrics_master_workers_Number{group=\"spark\", instance=\"master\", job=\"spark-master\"}  ",
     "legendFormat": "maxMem_MB"
    }
   ]
  },
  {
   "title": "No Of Cores Free By Worker",
   "type": "singlestat",
   "description": "No of currently running stages",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "metrics_worker_coresFree_Number{ group=\"spark\", instance=\"worker\", job=\"spark-worker\"}  ",
     "legendFormat": "maxMem_MB"
    }
   ]
  },
  {
   "title": "No Of Cores Used By Worker",
   "type": "singlestat",
   "description": "No of currently running stages",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "metrics_worker_coresUsed_Number{ group=\"spark\", instance=\"worker\", job=\"spark-worker\"}  "
    }
   ]
  },
  {
   "title": "Spark Driver Running Stages",
   "type": "graph",
   "description": "No of currently running stages",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_spark_app_driver_DAGScheduler_stage_runningStages_Number{group=\"spark\", instance=\"driver\", job=\"spark-driver\"} ",
     "legendFormat": "Running Stages"
    },
    {
     "expr": "metrics_spark_app_driver_DAGScheduler_stage_waitingStages_Number{group=\"spark\", instance=\"driver\", job=\"spark-driver\"} ",
     "legendFormat": "Waiting Stages"
    },
    {
     "expr": "metrics_spark_app_driver_DAGScheduler_stage_failedStages_Number{group=\"spark\", instance=\"driver\", job=\"spark-driver\"} ",
     "legendFormat": "Failed Stages"
    }
   ]
  },
  {
   "title": "Message Processing Time",
   "type": "graph",
   "description": "No of currently running stages",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_spark_app_driver_DAGScheduler_messageProcessingTime_Max{group=\"spark\", instance=\"driver\", job=\"spark-driver\"} ",
     "legendFormat": "Max"
    },
    {
     "expr": "metrics_spark_app_driver_DAGScheduler_messageProcessingTime_Min{group=\"spark\", instance=\"driver\", job=\"spark-driver\"} ",
     "legendFormat": "Min"
    },
    {
     "expr": "metrics_spark_app_driver_DAGScheduler_messageProcessingTime_Mean{group=\"spark\", instance=\"driver\", job=\"spark-driver\"} ",
     "legendFormat": "Mean"
    },
    {
     "expr": "metrics_spark_app_driver_DAGScheduler_messageProcessingTime_StdDev{group=\"spark\", instance=\"driver\", job=\"spark-driver\"} ",
     "legendFormat": "StdDev"
    }
   ]
  },
  {
   "title": "BlockManager",
   "type": "graph",
   "description": "No of currently running stages",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_spark_app_driver_BlockManager_memory_maxMem_MB_Number{group=\"spark\", instance=\"driver\", job=\"spark-driver\"} ",
     "legendFormat": "maxMem_MB"
    },
    {
     "expr": "metrics_spark_app_driver_BlockManager_disk_diskSpaceUsed_MB_Number{group=\"spark\", instance=\"driver\", job=\"spark-driver\"} ",
     "legendFormat": "diskSpaceUsed_MB"
    },
    {
     "expr": "metrics_spark_app_driver_BlockManager_memory_maxOnHeapMem_MB_Number{group=\"spark\", instance=\"driver\", job=\"spark-driver\"} ",
     "legendFormat": "maxOnHeapMem_MB"
    },
    {
     "expr": "metrics_spark_app_driver_BlockManager_memory_maxOffHeapMem_MB_Number{group=\"spark\", instance=\"driver\", job=\"spark-driver\"} ",
     "legendFormat": "maxOffHeapMem_MB"
    }
   ]
  },
  {
   "title": "Memory Free/Used by Worker",
   "type": "graph",
   "description": "No of currently running stages",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_worker_memFree_MB_Number{ group=\"spark\", instance=\"worker\", job=\"spark-worker\"}  ",
     "legendFormat": "memFree_MB"
    },
    {
     "expr": "metrics_worker_memUsed_MB_Number{ group=\"spark\", instance=\"worker\", job=\"spark-worker\"}  ",
     "legendFormat": "memUsed_MB"
    }
   ]
  },
  {
   "title": "LiveListenerBus listenerProcessingTime HeartbeatReceiver",
   "type": "graph",
   "description": "No of currently running stages",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_spark_app_driver_LiveListenerBus_listenerProcessingTime_org_apache_spark_HeartbeatReceiver_Count{type=\"timers\", group=\"spark\", instance=\"driver\", job=\"spark-driver\"}  ",
     "legendFormat": "Count"
    },
    {
     "expr": "metrics_spark_app_driver_LiveListenerBus_listenerProcessingTime_org_apache_spark_HeartbeatReceiver_Max{type=\"timers\", group=\"spark\", instance=\"driver\", job=\"spark-driver\"}  ",
     "legendFormat": "Max"
    },
    {
     "expr": "metrics_spark_app_driver_LiveListenerBus_listenerProcessingTime_org_apache_spark_HeartbeatReceiver_Mean{type=\"timers\", group=\"spark\", instance=\"driver\", job=\"spark-driver\"}  ",
     "legendFormat": "Mean"
    },
    {
     "expr": "metrics_spark_app_driver_LiveListenerBus_listenerProcessingTime_org_apache_spark_HeartbeatReceiver_Min{type=\"timers\", group=\"spark\", instance=\"driver\", job=\"spark-driver\"}  ",
     "legendFormat": "Min"
    }
   ]
  }
 ]
}